"""Markdown-first Research Vault filesystem mechanics."""

from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import fcntl
import hashlib
import json
import os
import re
import stat
import tempfile
import threading
import uuid
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from urllib.parse import quote, unquote, urlsplit


class VaultError(RuntimeError):
    """Base error for a Research Vault boundary violation."""


class ContainmentError(VaultError):
    """A path is outside the vault or follows an unsafe link."""


class ReservedPathError(VaultError):
    """A v1, product-owned, or unknown hidden path was targeted."""


class OwnershipError(VaultError):
    """A user-owned path was targeted by a vault mutation."""


class CASConflict(VaultError):
    """A target changed since the caller read its expected digest."""


class JournalError(VaultError):
    """An operation journal is incomplete, corrupt, or not recoverable."""


class PathClass(str, Enum):
    SEMANTIC = "semantic"
    SOURCE = "source"
    PERSISTENT_PROOF = "persistent-proof"
    DERIVED = "derived"
    TEMPORARY = "temporary"
    USER_OWNED = "user-owned"
    RESERVED = "reserved"
    VISIBLE_SUPPORT = "visible-support"


ROOT_DIRECTORIES = (
    "Inbox",
    "Sources",
    "Notes",
    "Projects",
    "Decisions",
    "Experiments",
    "Reviews",
    "Reports",
    "Views",
)

RESEARCH_DIRECTORIES = (
    "index",
    "evidence",
    "receipts",
    "operations",
    "experiments",
    "recovery",
    "cache",
    "logs",
    "locks",
)

DERIVED_RESEARCH_DIRECTORIES = {"index", "cache"}
PERSISTENT_RESEARCH_DIRECTORIES = {"evidence", "receipts", "operations", "experiments", "recovery"}
TEMPORARY_RESEARCH_DIRECTORIES = {"logs", "locks"}
RESERVED_TOP_LEVEL = {".git", "kb", ".agents", "record.yaml"}
USER_OWNED_TOP_LEVEL = {".obsidian"}
ID_RE = re.compile(r"[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\Z")
INLINE_LINK_RE = re.compile(r"(?<!!)\[[^\]]+\]\((?P<target><[^>]+>|[^)\s]+)(?:\s+[^)]*)?\)")
REFERENCE_LINK_RE = re.compile(r"^\[[^\]]+\]:\s*(?P<target><[^>]+>|\S+)", re.MULTILINE)
HEADING_RE = re.compile(r"^#{1,6}\s+(?P<title>.+?)\s*$", re.MULTILINE)
GENERATED_VIEW_MARKER = "<!-- Generated by research-vault; derived navigation only. -->"
_UNSET = object()


HOME_TEMPLATE = """# Research Home

## Start here

- [Inbox][inbox]
- [Active projects][active-projects]
- [Review queue][review-queue]
- [Recent sources][recent-sources]

## Current focus

- [Research Vault v2][vault-v2]

## Working conventions

- [Preferences][preferences]

[inbox]: Inbox/index.md
[active-projects]: Views/Active%20Projects.md
[review-queue]: Views/Review%20Queue.md
[recent-sources]: Views/Recent%20Sources.md
[vault-v2]: Projects/project-vault-v2/index.md
[preferences]: Preferences.md
"""

PREFERENCES_TEMPLATE = """# Preferences

This page contains human-readable working preferences for this vault.

Edit this Markdown directly. Mechanical settings and receipts, when needed,
belong in `.research/` and never replace the preferences written here.
"""

INBOX_TEMPLATE = """---
id: inbox
kind: inbox
status: active
---

# Inbox

Capture ideas, questions, and links here before they become durable research
objects.
"""

WELCOME_PROJECT_TEMPLATE = """---
id: project-vault-v2
kind: project
status: active
---

# Research Vault v2

## Research question

How can ordinary Markdown remain the only human semantic truth for research?

## Working notes

Use this starter page as a normal Markdown object. Add evidence, decisions,
and next actions visibly; hidden vault files only index, prove, or recover it.
"""


@dataclass(frozen=True)
class Page:
    path: Path
    page_id: str | None
    kind: str | None
    status: str | None
    title: str
    digest: str


@dataclass(frozen=True)
class VaultLayout:
    root: Path

    @property
    def home(self) -> Path:
        return self.root / "Home.md"

    @property
    def research(self) -> Path:
        return self.root / ".research"


def _absolute_root(root: Path) -> Path:
    return Path(os.path.abspath(os.fspath(root)))


def _relative_path(root: Path, target: Path | str) -> Path:
    root_path = _absolute_root(root)
    raw_target = os.fspath(target)
    if "\x00" in raw_target:
        raise ContainmentError("path contains a NUL byte")
    if "\\" in raw_target:
        raise ContainmentError("path must use POSIX separators")
    target_path = Path(raw_target)
    candidate = target_path if target_path.is_absolute() else root_path / target_path
    candidate = Path(os.path.abspath(os.fspath(candidate)))
    try:
        relative = candidate.relative_to(root_path)
    except ValueError as exc:
        raise ContainmentError(f"path escapes vault: {target}") from exc
    if not relative.parts:
        raise ContainmentError("vault root is not a file target")
    return relative


def _assert_root(root: Path) -> Path:
    root_path = _absolute_root(root)
    if root_path.exists():
        root_stat = root_path.lstat()
        if stat.S_ISLNK(root_stat.st_mode) or not stat.S_ISDIR(root_stat.st_mode):
            raise ContainmentError("vault root must be a real directory")
    return root_path


def _ensure_directory(root: Path, relative: Path | str) -> Path:
    """Create a vault directory one real path segment at a time."""

    root_path = _assert_root(root)
    if Path(relative) == Path("."):
        return root_path
    relative_path = _relative_path(root_path, relative)
    current = root_path
    for part in relative_path.parts:
        current = current / part
        try:
            metadata = current.lstat()
        except FileNotFoundError:
            current.mkdir()
            metadata = current.lstat()
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
            raise ContainmentError(f"directory path is not a real directory: {relative_path}")
    return current


def _assert_no_follow(root: Path, relative: Path) -> Path:
    root_path = _assert_root(root)
    current = root_path
    parts = relative.parts
    for index, part in enumerate(parts):
        current = current / part
        try:
            current_stat = current.lstat()
        except FileNotFoundError:
            break
        if stat.S_ISLNK(current_stat.st_mode):
            raise ContainmentError(f"symlink path segment is not allowed: {relative}")
        if index < len(parts) - 1 and not stat.S_ISDIR(current_stat.st_mode):
            raise ContainmentError(f"path segment is not a directory: {relative}")
    return root_path / relative


def _reserved_reason(relative: Path) -> str | None:
    parts = set(relative.parts)
    if parts & RESERVED_TOP_LEVEL:
        return "legacy or product-reserved path"
    if ".git" in parts:
        return "git metadata is not vault data"
    for index in range(len(relative.parts) - 1):
        if relative.parts[index : index + 2] == ("obsidian", "managed"):
            return "legacy Obsidian managed path"
    if relative.parts and relative.parts[0] == ".research":
        if len(relative.parts) == 1 or relative.parts[1] not in RESEARCH_DIRECTORIES:
            return "unknown .research path"
    if ".source" in relative.parts:
        source_index = relative.parts.index(".source")
        if source_index < 2 or relative.parts[0] != "Sources":
            return "source proof must belong to Sources/<source-id>/.source"
    for part in relative.parts:
        if part.startswith(".") and part not in {".research", ".source", ".obsidian"}:
            return "unknown hidden path"
    return None


def validate_target(root: Path, target: Path | str, *, for_write: bool = True) -> Path:
    """Validate and return an exact path inside the vault."""

    root_path = _assert_root(root)
    relative = _relative_path(root_path, target)
    reason = _reserved_reason(relative)
    if reason:
        raise ReservedPathError(f"{relative}: {reason}")
    if relative.parts[0] in USER_OWNED_TOP_LEVEL or relative.parts[0] == "AGENTS.md":
        if for_write:
            raise OwnershipError(f"user-owned path cannot be written: {relative}")
    path = _assert_no_follow(root_path, relative)
    try:
        target_stat = path.lstat()
    except FileNotFoundError:
        return path
    if stat.S_ISLNK(target_stat.st_mode):
        raise ContainmentError(f"symlink target is not allowed: {relative}")
    if stat.S_ISDIR(target_stat.st_mode):
        raise ContainmentError(f"directory is not a file target: {relative}")
    if not stat.S_ISREG(target_stat.st_mode):
        raise ContainmentError(f"special file is not a target: {relative}")
    return path


def classify_path(root: Path, target: Path | str) -> PathClass:
    """Classify a vault path without treating hidden data as semantic."""

    root_path = _assert_root(root)
    try:
        relative = _relative_path(root_path, target)
    except ContainmentError:
        return PathClass.RESERVED
    if _reserved_reason(relative):
        return PathClass.RESERVED
    parts = relative.parts
    if parts[0] in USER_OWNED_TOP_LEVEL or parts[0] == "AGENTS.md":
        return PathClass.USER_OWNED
    if ".source" in parts:
        return PathClass.SOURCE
    if parts[0] == ".research":
        category = parts[1] if len(parts) > 1 else ""
        if category in DERIVED_RESEARCH_DIRECTORIES:
            return PathClass.DERIVED
        if category in PERSISTENT_RESEARCH_DIRECTORIES:
            return PathClass.PERSISTENT_PROOF
        if category in TEMPORARY_RESEARCH_DIRECTORIES:
            return PathClass.TEMPORARY
        return PathClass.RESERVED
    if parts[0] == "Views" or relative.suffix == ".base":
        return PathClass.DERIVED
    if relative.suffix == ".md":
        return PathClass.SEMANTIC
    return PathClass.VISIBLE_SUPPORT


def is_semantic_path(root: Path, target: Path | str) -> bool:
    return classify_path(root, target) == PathClass.SEMANTIC


def _digest_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def file_digest(path: Path) -> str | None:
    """Return a regular file's SHA-256 digest, or ``None`` if absent."""

    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return None
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
        raise ContainmentError(f"digest target must be a regular file: {path}")
    return _digest_bytes(path.read_bytes())


def _payload_bytes(payload: str | bytes) -> bytes:
    if isinstance(payload, str):
        return payload.encode("utf-8")
    if isinstance(payload, bytes):
        return payload
    raise TypeError("payload must be str or bytes")


def _atomic_replace(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        path_metadata = path.lstat()
    except FileNotFoundError:
        path_metadata = None
    if path_metadata is not None and (
        stat.S_ISLNK(path_metadata.st_mode) or not stat.S_ISREG(path_metadata.st_mode)
    ):
        raise ContainmentError(f"atomic replacement target must be a regular file: {path}")
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary_path = Path(temporary.name)
            temporary.write(payload)
            temporary.flush()
            os.fsync(temporary.fileno())
        if path.exists() and not path.is_symlink():
            os.chmod(temporary_path, stat.S_IMODE(path.stat().st_mode))
        os.replace(temporary_path, path)
        temporary_path = None
        try:
            directory_fd = os.open(path.parent, os.O_DIRECTORY)
        except OSError:
            directory_fd = None
        if directory_fd is not None:
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
    finally:
        if temporary_path is not None:
            with contextlib.suppress(FileNotFoundError):
                temporary_path.unlink()


def atomic_write(
    path: Path,
    payload: str | bytes,
    *,
    expected_digest: str | None | object = _UNSET,
    root: Path | None = None,
) -> str:
    """Write exact bytes with replace semantics and an optional CAS check."""

    target = Path(path)
    vault_root = _assert_root(root) if root is not None else None
    if vault_root is not None:
        target = validate_target(vault_root, target)
        _ensure_directory(vault_root, target.parent.relative_to(vault_root))
    elif target.exists() and target.is_symlink():
        raise ContainmentError(f"symlink target is not allowed: {target}")
    current_digest = file_digest(target)
    if expected_digest is not _UNSET and current_digest != expected_digest:
        raise CASConflict(
            f"stale target {target}: expected {expected_digest!r}, found {current_digest!r}"
        )
    body = _payload_bytes(payload)
    _atomic_replace(target, body)
    return _digest_bytes(body)


def validate_id(page_id: str) -> str:
    if not isinstance(page_id, str) or not ID_RE.fullmatch(page_id):
        raise VaultError(f"invalid stable id: {page_id!r}")
    return page_id


def _frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        return {}, text
    lines = text.splitlines()
    closing_index = next(
        (index for index, line in enumerate(lines[1:], start=1) if line == "---"),
        None,
    )
    if closing_index is None:
        raise VaultError("frontmatter has no closing delimiter")
    fields: dict[str, str] = {}
    for line in lines[1:closing_index]:
        if not line.strip() or ":" not in line:
            raise VaultError(f"invalid frontmatter line: {line!r}")
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if key not in {"id", "kind", "status"} or not value or key in fields:
            raise VaultError(f"unsupported or duplicate frontmatter field: {key!r}")
        fields[key] = value
    if set(fields) != {"id", "kind", "status"}:
        raise VaultError("long-lived Markdown pages require id, kind, and status")
    validate_id(fields["id"])
    return fields, "\n".join(lines[closing_index + 1 :])


def parse_page(root: Path, path: Path | str) -> Page:
    target = validate_target(root, path, for_write=False)
    if target.suffix != ".md" or classify_path(root, target) != PathClass.SEMANTIC:
        raise VaultError(f"page must be visible semantic Markdown: {target}")
    content = target.read_text(encoding="utf-8")
    fields, body = _frontmatter(content)
    heading = HEADING_RE.search(body)
    title = heading.group("title").strip() if heading else target.stem
    relative = target.relative_to(_absolute_root(root))
    return Page(
        path=relative,
        page_id=fields.get("id"),
        kind=fields.get("kind"),
        status=fields.get("status"),
        title=title,
        digest=_digest_bytes(content.encode("utf-8")),
    )


def page_template(page_id: str, kind: str, status: str, title: str, body: str = "") -> str:
    validate_id(page_id)
    for field_name, value in (("kind", kind), ("status", status), ("title", title)):
        if not isinstance(value, str) or not value.strip() or "\n" in value:
            raise VaultError(f"invalid page {field_name}")
    normalized_body = body.rstrip()
    suffix = f"\n\n{normalized_body}" if normalized_body else ""
    return f"---\nid: {page_id}\nkind: {kind}\nstatus: {status}\n---\n\n# {title}{suffix}\n"


def create_page(
    root: Path,
    path: Path | str,
    *,
    page_id: str,
    kind: str,
    status: str,
    title: str,
    body: str = "",
) -> Page:
    target = validate_target(root, path)
    if target.suffix != ".md" or classify_path(root, target) != PathClass.SEMANTIC:
        raise OwnershipError("new pages must be visible semantic Markdown")
    validate_id(page_id)
    for existing in _iter_visible_pages(root):
        if existing.page_id == page_id:
            raise VaultError(f"stable id already exists at {existing.path}: {page_id}")
    digest = atomic_write(
        target,
        page_template(page_id, kind, status, title, body),
        expected_digest=None,
        root=root,
    )
    return Page(Path(target).relative_to(_absolute_root(root)), page_id, kind, status, title, digest)


def resolve_id(root: Path, page_id: str) -> Page:
    """Resolve identity by visible frontmatter, independent of the current path."""

    validate_id(page_id)
    matches = [page for page in _iter_visible_pages(root) if page.page_id == page_id]
    if not matches:
        raise VaultError(f"stable id does not exist: {page_id}")
    if len(matches) > 1:
        raise VaultError(f"stable id is ambiguous: {page_id}")
    return matches[0]


def stable_link(root: Path, source: Path | str, target: Path | str) -> str:
    root_path = _assert_root(root)
    source_path = validate_target(root_path, source, for_write=False)
    target_path = validate_target(root_path, target, for_write=False)
    relative = os.path.relpath(target_path, source_path.parent).replace(os.sep, "/")
    return quote(relative, safe="/._-#")


def _link_targets(text: str) -> list[str]:
    targets = [match.group("target") for match in INLINE_LINK_RE.finditer(text)]
    targets.extend(match.group("target") for match in REFERENCE_LINK_RE.finditer(text))
    return [target[1:-1] if target.startswith("<") and target.endswith(">") else target for target in targets]


def _resolve_link(root: Path, source: Path, raw_target: str) -> tuple[str, str] | None:
    parsed = urlsplit(raw_target)
    if parsed.scheme or parsed.netloc:
        return None
    target_text = unquote(parsed.path)
    if not target_text:
        target_path = source
    else:
        target_path = Path(os.path.normpath(os.path.join(source.parent.as_posix(), target_text)))
    relative = _relative_path(root, target_path)
    return relative.as_posix(), parsed.fragment


def _heading_anchors(text: str) -> set[str]:
    anchors: set[str] = set()
    counts: dict[str, int] = {}
    for match in HEADING_RE.finditer(text):
        slug = re.sub(r"[^\w\s-]", "", match.group("title").lower())
        slug = re.sub(r"[\s-]+", "-", slug).strip("-")
        if not slug:
            continue
        occurrence = counts.get(slug, 0)
        counts[slug] = occurrence + 1
        anchors.add(slug if occurrence == 0 else f"{slug}-{occurrence}")
    return anchors


def _iter_visible_pages(root: Path) -> list[Page]:
    root_path = _assert_root(root)
    pages: list[Page] = []
    for candidate in sorted(root_path.rglob("*.md")):
        relative = candidate.relative_to(root_path)
        if classify_path(root_path, relative) != PathClass.SEMANTIC:
            continue
        if candidate.is_symlink():
            raise ContainmentError(f"symlink Markdown page is not allowed: {relative}")
        pages.append(parse_page(root_path, relative))
    return pages


def _known_link_paths(root: Path, pages: list[Page]) -> set[str]:
    root_path = _assert_root(root)
    known = {page.path.as_posix() for page in pages}
    for candidate in sorted(root_path.rglob("*")):
        relative = candidate.relative_to(root_path)
        if relative.parts[0] in {".research", ".git", ".agents", ".obsidian"}:
            continue
        if candidate.is_symlink():
            raise ContainmentError(f"symlink vault entry is not allowed: {relative}")
        if candidate.is_file() or candidate.is_dir():
            known.add(relative.as_posix())
    return known


def _source_manifests(root: Path) -> list[dict[str, str]]:
    root_path = _assert_root(root)
    manifests: list[dict[str, str]] = []
    for candidate in sorted(root_path.glob("Sources/*/.source/manifest.json")):
        relative = candidate.relative_to(root_path)
        if candidate.is_symlink():
            raise ContainmentError(f"symlink source manifest is not allowed: {relative}")
        manifests.append({"path": relative.as_posix(), "digest": file_digest(candidate) or ""})
    return manifests


def _view_text(root: Path, view_name: str, pages: list[Page]) -> str:
    if view_name == "Active Projects.md":
        selected = [page for page in pages if page.kind == "project" and page.status == "active"]
    elif view_name == "Review Queue.md":
        selected = [
            page
            for page in pages
            if page.status in {"pending-review", "awaiting-decision", "ready-to-review"}
        ]
    else:
        selected = [page for page in pages if page.kind == "source"]
    selected.sort(key=lambda page: page.path.as_posix())
    lines = [GENERATED_VIEW_MARKER, f"# {view_name.removesuffix('.md')}", "", "This page is derived navigation; edit the linked Markdown object instead.", ""]
    if not selected:
        lines.append("- No matching pages yet.")
    else:
        for page in selected:
            link = stable_link(root, Path("Views") / view_name, page.path)
            lines.append(f"- [{page.title}]({link})")
    return "\n".join(lines) + "\n"


def _json_text(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def rebuild_index(root: Path, *, strict_links: bool = False) -> dict[str, object]:
    """Rebuild only derived index and View targets from visible Markdown."""

    root_path = _assert_root(root)
    pages = _iter_visible_pages(root_path)
    seen_ids: dict[str, Path] = {}
    for page in pages:
        if page.page_id is None:
            continue
        previous = seen_ids.get(page.page_id)
        if previous is not None:
            raise VaultError(f"duplicate stable id {page.page_id!r}: {previous} and {page.path}")
        seen_ids[page.page_id] = page.path

    known_paths = _known_link_paths(root_path, pages)
    links: list[dict[str, str]] = []
    link_errors: list[str] = []
    for page in pages:
        source_path = root_path / page.path
        text = source_path.read_text(encoding="utf-8")
        for raw_target in _link_targets(text):
            try:
                resolved = _resolve_link(root_path, page.path, raw_target)
            except ContainmentError as exc:
                link_errors.append(f"{page.path}: {raw_target}: {exc}")
                continue
            if resolved is None:
                continue
            target, fragment = resolved
            if target not in known_paths:
                link_errors.append(f"{page.path}: missing link target {raw_target}")
                continue
            if fragment and target.endswith(".md"):
                target_text = (root_path / target).read_text(encoding="utf-8")
                if fragment not in _heading_anchors(target_text):
                    link_errors.append(f"{page.path}: missing link anchor {raw_target}")
                    continue
            links.append({"source": page.path.as_posix(), "target": target, "fragment": fragment})
    if link_errors and strict_links:
        raise VaultError("invalid Markdown links: " + "; ".join(link_errors))

    pages_payload = [
        {
            "id": page.page_id,
            "kind": page.kind,
            "path": page.path.as_posix(),
            "status": page.status,
            "title": page.title,
        }
        for page in pages
    ]
    pages_payload.sort(key=lambda item: item["path"])
    links.sort(key=lambda item: (item["source"], item["target"], item["fragment"]))
    result: dict[str, object] = {
        "schema": "research-vault-index/v2",
        "pages": pages_payload,
        "links": links,
        "source_manifests": _source_manifests(root_path),
        "link_errors": link_errors,
    }

    targets = [
        root_path / ".research" / "index" / "pages.json",
        root_path / ".research" / "index" / "links.json",
        root_path / ".research" / "index" / "manifest.json",
    ]
    view_targets = [root_path / "Views" / name for name in ("Active Projects.md", "Review Queue.md", "Recent Sources.md")]
    for view_target in view_targets:
        if view_target.exists():
            existing = view_target.read_text(encoding="utf-8")
            if GENERATED_VIEW_MARKER not in existing:
                raise OwnershipError(f"derived view is user-owned after manual edit: {view_target.relative_to(root_path)}")
        targets.append(view_target)

    operation = begin_operation(root_path, "rebuild-index", targets)
    try:
        operation.write(targets[0], _json_text({"schema": result["schema"], "pages": pages_payload}))
        operation.write(targets[1], _json_text({"schema": result["schema"], "links": links}))
        operation.write(
            targets[2],
            _json_text({"schema": result["schema"], "source_manifests": result["source_manifests"]}),
        )
        for view_target in view_targets:
            operation.write(view_target, _view_text(root_path, view_target.name, pages))
        operation.commit()
    except BaseException:
        if not operation.closed:
            operation.abort()
        raise
    return result


def _operation_id() -> str:
    timestamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    return f"op-{timestamp}-{uuid.uuid4().hex[:12]}"


def _lock_path(root: Path, relative: Path) -> Path:
    token = hashlib.sha256(relative.as_posix().encode("utf-8")).hexdigest()
    return root / ".research" / "locks" / f"{token}.lock"


_held_locks: dict[tuple[int, str], tuple[object, int]] = {}
_held_locks_guard = threading.RLock()


class _ExactLocks:
    def __init__(self, root: Path, paths: list[Path]):
        self.root = root
        self.paths = paths
        self.acquired: list[tuple[int, str]] = []

    def acquire(self) -> None:
        thread_id = threading.get_ident()
        for relative in self.paths:
            key = (thread_id, relative.as_posix())
            with _held_locks_guard:
                held = _held_locks.get(key)
                if held is not None:
                    _held_locks[key] = (held[0], held[1] + 1)
                    self.acquired.append(key)
                    continue
                lock_path = _lock_path(self.root, relative)
                _ensure_directory(self.root, lock_path.parent.relative_to(self.root))
                _assert_no_follow(self.root, lock_path.relative_to(self.root))
                handle = None
                try:
                    descriptor = os.open(
                        lock_path,
                        os.O_CREAT | os.O_RDWR | getattr(os, "O_NOFOLLOW", 0),
                        0o600,
                    )
                    handle = os.fdopen(descriptor, "a+b")
                    fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
                except BaseException:
                    if handle is not None:
                        handle.close()
                    raise
                _held_locks[key] = (handle, 1)
                self.acquired.append(key)

    def release(self) -> None:
        thread_id = threading.get_ident()
        for key in reversed(self.acquired):
            with _held_locks_guard:
                held = _held_locks.get(key)
                if held is None:
                    continue
                if held[1] > 1:
                    _held_locks[key] = (held[0], held[1] - 1)
                    continue
                handle = held[0]
                with contextlib.suppress(OSError):
                    fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
                handle.close()
                del _held_locks[key]
        self.acquired.clear()


class VaultOperation:
    """An exact-target journaled mutation with rollback and CAS."""

    def __init__(self, root: Path, name: str, targets: list[Path | str], expected_digests: dict[Path | str, str | None] | None = None):
        self.root = _assert_root(root)
        self.name = name
        if not isinstance(name, str) or not name or "/" in name or "\\" in name:
            raise JournalError("operation name must be a simple non-empty label")
        target_paths = [validate_target(self.root, target) for target in targets]
        if not target_paths:
            raise JournalError("operation target set must be non-empty")
        relative_targets = sorted({path.relative_to(self.root) for path in target_paths}, key=lambda item: item.as_posix())
        if len(relative_targets) != len(target_paths):
            raise JournalError("operation target set contains duplicate paths")
        self.targets = relative_targets
        expected = expected_digests or {}
        self.expected_digests = {
            relative.as_posix(): expected.get(
                relative,
                expected.get(relative.as_posix(), expected.get(self.root / relative, _UNSET)),
            )
            for relative in relative_targets
        }
        self.operation_id = _operation_id()
        self.operation_dir = self.root / ".research" / "operations" / self.operation_id
        self.recovery_dir = self.root / ".research" / "recovery" / self.operation_id
        self.journal_path = self.operation_dir / "journal.json"
        self._locks = _ExactLocks(self.root, self.targets)
        self.closed = False
        self._start()

    def _write_journal(self, entry: dict[str, object]) -> None:
        _ensure_directory(self.root, self.operation_dir.relative_to(self.root))
        _atomic_replace(self.journal_path, _json_text(entry).encode("utf-8"))

    def _load_journal(self) -> dict[str, object]:
        try:
            value = json.loads(self.journal_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise JournalError(f"cannot load operation journal {self.operation_id}") from exc
        if not isinstance(value, dict):
            raise JournalError("operation journal must be an object")
        return value

    def _start(self) -> None:
        self._locks.acquire()
        try:
            before_digests: dict[str, str | None] = {}
            for relative in self.targets:
                target = _assert_no_follow(self.root, relative)
                digest = file_digest(target)
                expected = self.expected_digests[relative.as_posix()]
                if expected is not _UNSET and digest != expected:
                    raise CASConflict(
                        f"stale target {relative}: expected {expected!r}, found {digest!r}"
                    )
                before_digests[relative.as_posix()] = digest
            _ensure_directory(self.root, self.recovery_dir.relative_to(self.root))
            before_files: dict[str, str] = {}
            for relative in self.targets:
                target = self.root / relative
                if before_digests[relative.as_posix()] is not None:
                    recovery_path = self.recovery_dir / f"{hashlib.sha256(relative.as_posix().encode('utf-8')).hexdigest()}.before"
                    _atomic_replace(recovery_path, target.read_bytes())
                    before_files[relative.as_posix()] = recovery_path.relative_to(self.root).as_posix()
            self._write_journal(
                {
                    "schema": "research-vault-operation/v2",
                    "operation_id": self.operation_id,
                    "name": self.name,
                    "state": "active",
                    "stage": "preflight",
                    "target_paths": [relative.as_posix() for relative in self.targets],
                    "before_digests": before_digests,
                    "after_digests": {},
                    "before_files": before_files,
                    "checkpoint": {"paths": [relative.as_posix() for relative in self.targets]},
                }
            )
        except BaseException:
            self._locks.release()
            raise

    def _update(self, **updates: object) -> None:
        entry = self._load_journal()
        entry.update(updates)
        self._write_journal(entry)

    def write(self, path: Path | str, payload: str | bytes) -> str:
        if self.closed:
            raise JournalError("operation is closed")
        relative = _relative_path(self.root, path)
        if relative not in self.targets:
            raise JournalError(f"target is outside operation target set: {relative}")
        target = validate_target(self.root, relative)
        current = file_digest(target)
        entry = self._load_journal()
        after_digests = dict(entry.get("after_digests", {}))
        expected = after_digests.get(relative.as_posix(), entry["before_digests"][relative.as_posix()])
        digest = atomic_write(target, payload, expected_digest=expected, root=self.root)
        after_digests[relative.as_posix()] = digest
        self._update(stage="write", after_digests=after_digests)
        return digest

    def _restore_before(self, entry: dict[str, object], state: str) -> None:
        before_digests = entry.get("before_digests")
        if not isinstance(before_digests, dict):
            raise JournalError("operation journal has no before digests")
        after_digests = entry.get("after_digests")
        if not isinstance(after_digests, dict):
            after_digests = {}
        before_files = entry.get("before_files")
        if not isinstance(before_files, dict):
            before_files = {}
        restore_plan: list[tuple[Path, str | None, bytes | None]] = []
        for relative_text in [relative.as_posix() for relative in self.targets]:
            relative = Path(relative_text)
            target = validate_target(self.root, relative)
            expected_current = after_digests.get(relative_text, before_digests.get(relative_text))
            current = file_digest(target)
            if current != expected_current:
                raise CASConflict(
                    f"recovery stopped at {relative}: expected {expected_current!r}, found {current!r}"
                )
            before_digest = before_digests.get(relative_text)
            if before_digest is None:
                restore_plan.append((target, None, None))
                continue
            recovery_relative = before_files.get(relative_text)
            if not isinstance(recovery_relative, str):
                raise JournalError(f"missing recovery snapshot for {relative}")
            recovery_path = validate_target(self.root, recovery_relative, for_write=False)
            restored = recovery_path.read_bytes()
            if _digest_bytes(restored) != before_digest:
                raise JournalError(f"recovery snapshot digest mismatch for {relative}")
            restore_plan.append((target, before_digest, restored))
        for target, before_digest, restored in reversed(restore_plan):
            if before_digest is None:
                if target.exists():
                    target.unlink()
                continue
            assert restored is not None
            _atomic_replace(target, restored)
        self._update(state=state, stage="recovered", after_digests={})

    def commit(self) -> None:
        if self.closed:
            raise JournalError("operation is closed")
        try:
            entry = self._load_journal()
            after_digests = dict(entry.get("after_digests", {}))
            before_digests = entry.get("before_digests", {})
            for relative in self.targets:
                relative_text = relative.as_posix()
                current = file_digest(self.root / relative)
                expected_current = after_digests.get(relative_text, before_digests.get(relative_text))
                if current != expected_current:
                    self._update(stage="conflict")
                    raise CASConflict(
                        f"commit stopped at {relative}: expected {expected_current!r}, found {current!r}"
                    )
                after_digests.setdefault(relative_text, current)
            self._update(
                state="commit",
                stage="commit",
                after_digests=after_digests,
                checkpoint={"paths": [relative.as_posix() for relative in self.targets]},
            )
        finally:
            self._locks.release()
            self.closed = True

    def abort(self) -> None:
        if self.closed:
            return
        try:
            entry = self._load_journal()
            self._restore_before(entry, "abort")
        finally:
            self._locks.release()
            self.closed = True

    def abandon(self) -> None:
        """Release locks while retaining an active journal for crash recovery."""

        if not self.closed:
            self._locks.release()
            self.closed = True

    def __enter__(self) -> VaultOperation:
        return self

    def __exit__(self, exception_type: object, exception: object, traceback: object) -> bool:
        if self.closed:
            return False
        if exception_type is None:
            self.commit()
        else:
            self.abort()
        return False


def begin_operation(
    root: Path,
    name: str,
    targets: list[Path | str],
    *,
    expected_digests: dict[Path | str, str | None] | None = None,
) -> VaultOperation:
    return VaultOperation(root, name, targets, expected_digests)


@contextlib.contextmanager
def journaled_operation(
    root: Path,
    name: str,
    targets: list[Path | str],
    *,
    expected_digests: dict[Path | str, str | None] | None = None,
):
    operation = begin_operation(root, name, targets, expected_digests=expected_digests)
    try:
        yield operation
    except BaseException:
        if not operation.closed:
            operation.abort()
        raise
    else:
        if not operation.closed:
            operation.commit()


def load_operation(root: Path, operation_id: str) -> dict[str, object]:
    if not re.fullmatch(r"op-[0-9TZ]+-[0-9a-f]+", operation_id):
        raise JournalError("invalid operation id")
    path = _assert_root(root) / ".research" / "operations" / operation_id / "journal.json"
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise JournalError(f"cannot load operation journal {operation_id}") from exc
    if not isinstance(value, dict) or value.get("operation_id") != operation_id:
        raise JournalError("operation journal identity mismatch")
    return value


def recover_operation(root: Path, operation_id: str) -> dict[str, object]:
    """Restore an active operation's exact before-images after a crash."""

    root_path = _assert_root(root)
    entry = load_operation(root_path, operation_id)
    state = entry.get("state")
    if state in {"commit", "abort", "recovered"}:
        return entry
    targets = entry.get("target_paths")
    if not isinstance(targets, list) or not targets or not all(isinstance(item, str) for item in targets):
        raise JournalError("operation journal has invalid target paths")
    operation = object.__new__(VaultOperation)
    operation.root = root_path
    operation.targets = [Path(item) for item in targets]
    operation.operation_id = operation_id
    operation.operation_dir = root_path / ".research" / "operations" / operation_id
    operation.recovery_dir = root_path / ".research" / "recovery" / operation_id
    operation.journal_path = operation.operation_dir / "journal.json"
    operation.closed = False
    operation._locks = _ExactLocks(root_path, operation.targets)
    operation._locks.acquire()
    try:
        operation._restore_before(entry, "recovered")
        return load_operation(root_path, operation_id)
    finally:
        operation._locks.release()
        operation.closed = True


def _create_if_absent(root: Path, path: Path, content: str) -> None:
    target = validate_target(root, path)
    if target.exists():
        return
    atomic_write(target, content, expected_digest=None, root=root)


def _ensure_layout_directories(root: Path) -> None:
    for directory in ROOT_DIRECTORIES:
        _ensure_directory(root, directory)
    for directory in RESEARCH_DIRECTORIES:
        _ensure_directory(root, Path(".research") / directory)


def initialize_vault(root: Path) -> VaultLayout:
    """Create a safe fresh-vault layout without replacing user Markdown."""

    root_path = _absolute_root(root)
    root_path.mkdir(parents=True, exist_ok=True)
    _assert_root(root_path)
    entries = {entry.name for entry in root_path.iterdir()}
    legacy_entries = sorted(name for name in entries if name in {"kb", "record.yaml", "obsidian"})
    if legacy_entries:
        raise ReservedPathError(f"legacy workspace cannot be initialized: {legacy_entries}")
    if entries and "Home.md" not in entries:
        infrastructure = {".agents", ".git", ".gitignore", ".obsidian", "AGENTS.md"}
        collisions = sorted(entries - infrastructure)
        if collisions:
            raise VaultError(
                "fresh-vault initialization requires an empty/infrastructure-only root "
                f"or existing Home.md; found {collisions}"
            )
    _ensure_layout_directories(root_path)
    initial_files = {
        Path("Home.md"): HOME_TEMPLATE,
        Path("Preferences.md"): PREFERENCES_TEMPLATE,
        Path("Inbox/index.md"): INBOX_TEMPLATE,
        Path("Projects/project-vault-v2/index.md"): WELCOME_PROJECT_TEMPLATE,
    }
    welcome_page = Page(
        Path("Projects/project-vault-v2/index.md"),
        "project-vault-v2",
        "project",
        "active",
        "Research Vault v2",
        _digest_bytes(WELCOME_PROJECT_TEMPLATE.encode("utf-8")),
    )
    view_files = {
        Path("Views/Active Projects.md"): _view_text(root_path, "Active Projects.md", [welcome_page]),
        Path("Views/Review Queue.md"): _view_text(root_path, "Review Queue.md", []),
        Path("Views/Recent Sources.md"): _view_text(root_path, "Recent Sources.md", []),
    }
    targets = [path for path in [*initial_files, *view_files] if not (root_path / path).exists()]
    if targets:
        operation = begin_operation(root_path, "initialize-vault", targets)
        try:
            for path, content in {**initial_files, **view_files}.items():
                if path in targets:
                    operation.write(path, content)
            operation.commit()
        except BaseException:
            if not operation.closed:
                operation.abort()
            raise
    return VaultLayout(root_path)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    init_parser = subparsers.add_parser("init")
    init_parser.add_argument("root", type=Path)
    index_parser = subparsers.add_parser("rebuild-index")
    index_parser.add_argument("root", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = _parser().parse_args(argv)
    if arguments.command == "init":
        initialize_vault(arguments.root)
        return 0
    if arguments.command == "rebuild-index":
        rebuild_index(arguments.root)
        return 0
    raise AssertionError(arguments.command)


if __name__ == "__main__":
    raise SystemExit(main())
